export enum SocketEventEnum {
  SOCKET_CONNECTION_STATUS = "socket_connection_status",
  ROOM_JOINED = "room_joined",
  ROOM_LEAVED = "room_leaved",
  EVENT_STARTED = "event_started",
  EVENT_ENDED = "event_ended",
  EVENT_LEAVED = "event_leaved",
  EVENT_JOINED = "event_joined",
  ATTENDEE_PROFILE_CARD_BANNER_CHANGED = "attendee_profile_card_banner_changed",
  ADVERTISE_CAROUSEL_BANNER_CHANGED = "advertise_carousel_banner_changed",
  ADVERTISE_CAROUSEL_SETTING_CHANGED = "advertise_carousel_setting_changed",
  ADVERTISE_CAROUSEL_BANNER_DELETED = "advertise_carousel_banner_deleted",
  ADVERTISE_CAROUSEL_BANNER_ADDED = "advertise_carousel_banner_added",
  RECEIVE_LIVE_CHAT_MESSAGE = "receive_live_chat_message",
  RECEIVE_NEW_MESSENGER = "receive_new_messenger",
  RECEIVE_MESSAGE = "receive_message",
  AVAILABLE_FOR_SIDECHAT = "user_available_for_sidechat",
  USER_PROFILE_IMAGE_CHANGED = "user_profile_image_changed",
  USER_PROFILE_DATA_CHANGED = "user_profile_data_changed",
  EVENT_LIVE_CHAT_CHANGED = "event_live_chat_changed",
  EVENT_SIDE_CHAT_AUDIO_CHANGED = "event_side_chat_audio_changed",
  EVENT_SIDE_CHAT_VIDEO_CHANGED = "event_side_chat_video_changed",
  CURRENT_STREAMING_CONTENT_CHANGED = "current_streaming_content_changed",
  AVAILABLE_FOR_LIVEQA = "hand_raise_or_lower",
  EVENT_USER_DEACTIVATED = 'event_user_deactivated',
  BLOCK_USER_CHANGED = 'block_user_changed',
  ADVERTISE_CAROUSEL_BANNER_REDIRECT_URL_CHANGED = 'advertise_carousel_banner_redirect_url_changed',
}
