export enum StepEnum{
  WHATS_YOUR_NAME = 'WHATS_YOUR_NAME',
  WHAT_WE_CALL_YOUR_FANSPACE = 'WHAT_WE_CALL_YOUR_FANSPACE',
  SELECT_FANSPACE = 'SELECT_FANSPACE',
  NONE = 'NONE',
  CREATE_NEW_FANSPACE = 'CREATE_NEW_FANSPACE'
}
